### ISSUE TITLE
need to remove members from groups as well

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/member-group-processor#2]
When a community element is "false" remove the member from the group:

```
"data": [
      {
        "cognitive": true,
        "blockchain": true,
        "ios": true,
        "predix": false
      }
    ]
```

See DELETE op for removing members [here](https://github.com/appirio-tech/tc1-api-core/blob/dev/tech.core/tech.core.service.identity/doc/groups-api-docs.md)
steps should be: 
- look up group Id
- find member in group 
- use membership Id from group member list to `DELETE` member from group

**Comment by callmekatootie** [comment]
:+1: Shall we close the ticket?
