### ISSUE TITLE
switch statement should compare on lower case

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/member-group-processor#23]
[this](https://github.com/topcoder-platform/member-group-processor/blob/fb751e22c45bc0ff34b95cc9d80f9fb0f6302e4a/src/services/ProcessorService.js#L137) line compares on a capitalized case statement. should lowercase the input and the case statements for safety

**Comment by dushyantb** [comment]
not required as the code has been modified to [this](https://github.com/topcoder-platform/member-group-processor/blob/09bbc3b5aad75a9c00bf77c3515c8ac4e356a871/src/services/ProcessorService.js#L128)
