### ISSUE TITLE
Closed Community add should be config driven

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/member-group-processor#24]
We should probably not rely on a hard coded set of cases [here](https://github.com/topcoder-platform/member-group-processor/blob/master/src/services/ProcessorService.js#L131)
Maybe we should just always search for the ssoId field on the group and add them?

**Comment by cwdcwd** [comment]
@dushyantb thoughts on this?

**Comment by dushyantb** [comment]
@cwdcwd it's already implemented and deployed on `dev`
